# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Coder Geass' Blog
author:
  name: Coder Geass
  email: codergeass@outlook.com
  weibo: http://weibo.com
  zhihu: http://zhihu.com
  twitter: http://twitter.com
  github: http://github.com
tagline: Enjoy Life!
modified: 2017-9-26
description: This is a static website for Coder Geass to write and share his blogs
  # this means to ignore newlines until "baseurl:"
  # Write an awesome description for your new site here. You can edit this
  # line in _config.yml. It will appear in your document head meta (for
  # Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://codergeass.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: codergeass
github_username: codergeass

pages_list:
  Home: '/'
  Articles: '/articles'
  Projects: '/prjects'
  About: '/about'
  Feed: '/atom.xml'

paginate_langs: ["en", "cn"]

exclude: README.md

# Build settings
markdown: kramdown
excerpt_separator: "<!--break-->"
# redcarpet:
#   extensions: ["footnotes", "no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
# highlighter: pygments

# theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-watch
  - jekyll-paginate
# This will require each of these gems automatically.

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

permalink: /articles/:year/:month/:day/:title
# paginate: 5

sitemap:
  filename: "/sitemap.xml"
  exclude:
    - "/atom.xml"
  include_posts:
    - "/index.html"
    - "/about.html"
    - "/articles.html"
    - "/projects.html"
    - "/cv.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"
